# Your lab name
title: UBC DAIS Lab - Bhushan Gopaluni
labname: UBC Data Analytics and Intelligent Systems Lab
tagline: Paving the way for the next industrial revolution through data
location: Vancouver, BC, Canada
labshortname: DAIS Lab
unishortname: UBC
url: "https://dais.chbe.ubc.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username: daisubc
footer_desc: |
  The UBC Data Analytics and Intelligent Systems Lab is based in Vancouver, BC, Canada. Our lab conducts research at the intersection of process control, data analytics 
  and machine learning. 

  We develop novel algorithms and computational tools 
  to bring a new level of automation to the process industry.

# Your name
name: Bhushan Gopaluni
department: Department of Chemical & Biological Engineering
depturl: https://chbe.ubc.ca/
university: University of British Columbia (UBC)
jobtitle: Professor
secondjobtitle: Associate Dean, Education and Professional Development
faculty: Faculty of Applied Science
facultyprofile: https://engineering.ubc.ca/profile/bhushan-gopaluni
facultyurl: https://apsc.ubc.ca/
profilepic: https://dais.chbe.ubc.ca/assets/profile/bhushan.jpg

# Your address and contact
email: bhushan.gopaluni@ubc.ca
phone: 604-827-5668
office: KAISER 5018
address: 5000-2332 Main Mall
postalcode: V6T 1Z4
city: Vancouver
region: British Columbia

# Short bio for front page
shortbio: >-
  leads research activities at the UBC DAIS Lab. 
  He is a Professor in the Department of Chemical and Biological Engineering and 
  Associate Dean, Education and Professional Development 
  in the Faculty of Applied Science at the University of British Columbia (UBC).

description: >- # this means to ignore newlines until "baseurl:"
  The UBC DAIS Lab conducts research at the intersection of process control, data analytics 
  and machine learning. We develop novel algorithms and computational tools 
  to bring a new level of automation to the process industry. 

# For google search console
googleverification: Uhr-tsoENf7WIxvNZZ6G7PWLp2_kZMrJ5tCOfBbTGXw

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: ./_scss

collections: 
  profiles:
    output: true
    permalink: /people/:name/
  news:
    output: true
    permalink: /news/:path/ 
  publications:
    output: true
    permalink: /publications/:path/
  research:
    output: true
    permalink: /research/:path/
  papers:
    output: true
    permalink: /publication/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
